[package]
name = "slap"
version = "0.1.0"
authors = ["5hir0kur0 <12101162+5hir0kur0@users.noreply.github.com>"]
edition = "2018"

[dependencies]
portaudio = "0.7.0"
rustfft = "3.0.0"
sdl2 = {version="0.32.2", default-features=false, features=['gfx']}
